---
hosts:
  -
    settings:
      hostname: core_provisioner
      domain: startcloud.com
      server_id: '4020'
      consoleport: 4020
      consolehost: 0.0.0.0
      box: 'STARTcloud/debian12-server'
      box_version: 0.0.3
      setup_wait: 300
      vagrant_user_private_key_path: ./core/ssh_keys/id_rsa
      vagrant_user: startcloud
      vagrant_user_pass: 'STARTcloud22@!'

