name: MANUAL - Merge-Submodule

on:
#  push:
#    branches:
#      - submodule 
  workflow_dispatch:

jobs:
  merge-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge submodule into main
        run: |
          git fetch --unshallow
          git checkout submodule
          git pull
          git checkout main
          git merge --no-ff submodule -m "Merge submodule into main"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: submodule
          title: Merge submodule into main
          body: |
            This PR merges the submodule branch into the main branch.
            Please review the changes.
          branch: merge-submodule-main