name: MANUAL - Merge-Submodule

on:
#  push:
#    branches:
#      - submodule 
  workflow_dispatch:

jobs:
  merge-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Status
        run: git status

      - name: Switch to submodule branch
        run: git checkout submodule
      
      - name: Merge submodule into main
        run: |
          git checkout main
          git merge submodule --commit --no-edit
      
      - name: Push merged changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main